# Generated by Django 5.2.1 on 2025-06-02 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biagent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customers',
        ),
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
        migrations.AlterModelTable(
            name='review',
            table='reviews',
        ),
    ]
